---
- name: Deploy Scheme Manager on AWS
  hosts: scheme_mgmt_pro
  user: ec2-user

  tasks:
    - name: Clone the source from github
      git:
        repo: https://github.com/amtsh/indiangovtschemes.git
        dest: "{{ work_dir }}/indiangovtschemes"
        version: master

    - name: Build source
      shell: ./gradlew clean build -x test
      args:
        chdir: "{{ work_dir }}/indiangovtschemes"

    - name: Check if java process is running
      shell: ps -ef | grep java | grep 'govtschemes' | grep -v 'grep' | wc -l
      register: is_running

    - name: Get process ID of java process
      shell: ps -ef | grep java | grep 'govtschemes' | grep -v 'grep' | awk '{print $2}'
      register: java_process_id
      when: is_running.stdout == "1"

    - name: Stop java process
      shell: kill -9 {{ java_process_id.stdout }}
      when: is_running.stdout == "1"

    - name: Ensure service dir exists
      file:
        path: "{{ service_dir }}"
        state: directory

    - name: Release static assets
      shell: cp -r "{{ build_dir }}/{{ assets_dir }}" "{{ service_dir }}"

    - name: Deploy jar
      copy:
        remote_src: True
        src: "{{ work_dir }}/indiangovtschemes/{{ jar_build_path }}"
        dest: "{{ service_dir }}"

    - name: Start java process
      shell: nohup java -Dspring.profiles.active=production -jar govtschemes-0.0.1-SNAPSHOT.jar --spring.data.mongodb.uri=`cat $HOME/env.txt` > start.log &
      args:
        chdir: "{{ service_dir }}"
